name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: true

jobs:
  main:
    name: Test
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Run Tests
        run: ./run_tests.sh
