name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - Sources/**
      - Tests/**
      - .github/workflows/test.yaml
  pull_request:
    branches: [main]
    paths:
      - Sources/**
      - Tests/**
      - .github/workflows/test.yaml

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Configure cache
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/Homebrew/xcbeautify*
            ~/Library/Caches/Homebrew/downloads/*xcbeautify*
            ~/Library/Developer/Xcode/DerivedData/ios-client-sdk*
          key: ios-cache-
          restore-keys: ios-cache-

      - name: Install XCBeautify
        run: brew install xcbeautify

      - name: Build
        run: |
          cd .swiftpm/xcode
          xcodebuild build -workspace package.xcworkspace -scheme Statsig -destination "platform=iOS Simulator,name=iPhone SE (2nd generation)" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcbeautify && exit ${PIPESTATUS[0]}

      - name: Build macOS
        run: |
          cd .swiftpm/xcode
          xcodebuild build -workspace package.xcworkspace -scheme Statsig -destination "platform=macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcbeautify && exit ${PIPESTATUS[0]}

      - name: Test Internal Store
        run: |
          cd .swiftpm/xcode
          xcodebuild test -only-testing:StatsigTests/InternalStoreSpec -workspace package.xcworkspace -scheme Statsig -destination "platform=iOS Simulator,name=iPhone SE (2nd generation)" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcbeautify && exit ${PIPESTATUS[0]}

      - name: Test Statsig
        run: |
          cd .swiftpm/xcode
          xcodebuild test -only-testing:StatsigTests/StatsigSpec -workspace package.xcworkspace -scheme Statsig -destination "platform=iOS Simulator,name=iPhone SE (2nd generation)" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcbeautify && exit ${PIPESTATUS[0]}

      - name: Test Everything Else
        run: |
          cd .swiftpm/xcode
          xcodebuild test -skip-testing:StatsigTests/InternalStoreSpec -skip-testing:StatsigTests/StatsigSpec -workspace package.xcworkspace -scheme Statsig -destination "platform=iOS Simulator,name=iPhone SE (2nd generation)" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcbeautify && exit ${PIPESTATUS[0]}
