name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - Sources/**
      - Tests/**
      - .github/workflows/test.yaml
  pull_request:
    branches: [main]
    paths:
      - Sources/**
      - Tests/**
      - .github/workflows/test.yaml

env:
  CODE_SIGNING_REQUIRED: NO
  CODE_SIGN_IDENTITY: ""

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install XCBeautify
        run: brew install xcbeautify

      - name: Configure cache
        uses: actions/cache@v3
        with:
          path: build
          key: ios-cache-
          restore-keys: ios-cache-

      - name: Run Build iOS
        run: |
          cd .swiftpm/xcode
          xcodebuild build -destination "platform=iOS Simulator,name=iPhone SE (2nd generation)" -workspace package.xcworkspace -scheme Statsig -derivedDataPath "build" | xcbeautify && exit ${PIPESTATUS[0]}

      - name: Run Build macOS
        run: |
          cd .swiftpm/xcode
          xcodebuild build -destination "platform=macOS" -workspace package.xcworkspace -scheme Statsig -derivedDataPath "build" | xcbeautify && exit ${PIPESTATUS[0]}

      - name: Run Tests
        run: ./run_tests.sh
