on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - Sources/**
      - Tests/**
      - .github/workflows/tests.yml
  pull_request:
    branches: [main]
    paths:
      - Sources/**
      - Tests/**
      - .github/workflows/tests.yml

name: Test
jobs:
  test:
    name: Test
    runs-on: macos-latest
    timeout-minutes: 15
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=15.2,name=iPhone 12 Pro']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install XCBeautify
        run: brew install xcbeautify
      - name: Build and test
        run: |
          cd .swiftpm/xcode
          xcodebuild clean test -workspace package.xcworkspace -scheme Statsig -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcbeautify && exit ${PIPESTATUS[0]}
        env:
          destination: ${{ matrix.destination }}
