name: Testbed UI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - Sources/**
      - Tests/**
      - .github/workflows/testbed-ui-tests.yaml
  pull_request:
    branches: [main]
    paths:
      - Sources/**
      - Tests/**
      - .github/workflows/testbed-ui-tests.yaml

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Configure Homebrew cache
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/Homebrew/xcbeautify*
            ~/Library/Caches/Homebrew/downloads/*xcbeautify*
          key: ios-brew-
          restore-keys: ios-brew-

      - name: Install XCBeautify
        run: brew install xcbeautify

      - name: Build and Test
        run: |
          STATSIG_CLIENT_KEY=$STATSIG_CLIENT_KEY \
            xcodebuild clean test \
            -scheme ios-sdk-testbed \
            -project ios-sdk-testbed/ios-sdk-testbed.xcodeproj/ \
            -configuration Debug \
            -destination "platform=iOS Simulator,name=iPod touch (7th generation)" \
            | xcbeautify && exit ${PIPESTATUS[0]}
        env:
          STATSIG_CLIENT_KEY: ${{ secrets.IOS_SDK_E2E_CLIENT_KEY }}
